name: Merge on LGTM Label
on:
  schedule:
    - cron: "*/30 * * * *"
jobs:
  merge-checker:
    runs-on: ubuntu-latest
    env:
      ROBOT_PAT: ${{ secrets.ROBOT_PAT }}
    steps:
      - uses: chnsz/prow-github-actions@v1.0.0
        if: ${{ env.ROBOT_PAT }}
        with:
          jobs: 'lgtm'
          github-token: "${{ env.ROBOT_PAT }}"
          # this configuration is optional and will default to 'merge'
          # possible options are 'merge', 'rebase', or 'squash'
          merge-method: 'squash'
